local itemMountDollId = 28895 -- Mantendo o mesmo ID, mas podemos mudar se precisar

local mounts = {
    [1] = "Widow Queen", -- Mantendo os nomes para facilitar a identificação, mas estes devem ser os nomes INTERNOS das montarias
    [2] = "Racing Bird",
    [3] = "War Bear",
    [4] = "Black Sheep",
    [5] = "Midnight Panther",
    [6] = "Draptor",
    [7] = "Titanica",
    [8] = "Tin Lizzard",
    [9] = "Blazebringer",
    [10] = "Rapid Boar",
    [11] = "Stampor",
    [12] = "Undead Cavebear",
    [13] = "Donkey",
    [14] = "Tiger Slug",
    [15] = "Uniwheel",
    [16] = "Crystal Wolf",
    [17] = "War Horse",
    [18] = "Kingly Deer",
    [19] = "Tamed Panda",
    [20] = "Dromedary",
    [21] = "Scorpion King",
    [22] = "Rented Horse",
    [23] = "Armoured War Horse",
    [24] = "Shadow Draptor",
    [25] = "Rented Horse (Gray)",
    [26] = "Rented Horse (Brown)",
    [27] = "Lady Bug",
    [28] = "Manta Ray",
    [29] = "Ironblight",
    [30] = "Magma Crawler",
    [31] = "Dragonling",
    [32] = "Gnarlhound",
    [33] = "Crimson Ray",
    [34] = "Steelbeak",
    [35] = "Water Buffalo",
    [36] = "Tombstinger",
    [37] = "Platesaurian",
    [38] = "Ursagrodon",
    [39] = "The Hellgrip",
    [40] = "Noble Lion",
    [41] = "Desert King",
    [42] = "Shock Head",
    [43] = "Walker",
    [44] = "Azudocus",
    [45] = "Carpacosaurus",
    [46] = "Death Crawler",
    [47] = "Flamesteed",
    [48] = "Jade Lion",
    [49] = "Jade Pincer",
    [50] = "Nethersteed",
    [51] = "Tempest",
    [52] = "Winter King",
    [53] = "Doombringer",
    [54] = "Woodland Prince",
    [55] = "Hailstorm Fury",
    [56] = "Siegebreaker",
    [57] = "Poisonbane",
    [58] = "Blackpelt",
    [59] = "Golden Dragonfly",
    [60] = "Steel Bee",
    [61] = "Copper Fly",
    [62] = "Tundra Rambler",
    [63] = "Highland Yak",
    [64] = "Glacier Vagabond",
    [65] = "Flying Divan",
    [66] = "Magic Carpet",
    [67] = "Floating Kashmir",
    [68] = "Ringtail Waccoon",
    [69] = "Night Waccoon",
    [70] = "Emerald Waccoon",
    [71] = "Glooth Glider",
    [72] = "Shadow Hart",
    [73] = "Black Stag",
    [74] = "Emperor Deer",
    [75] = "Flitterkatzen",
    [76] = "Venompaw",
    [77] = "Batcat",
    [78] = "Sea Devil",
    [79] = "Coralripper",
    [80] = "Plumfish",
    [81] = "Gorongra",
    [82] = "Noctungra",
    [83] = "Silverneck",
    [84] = "Slagsnare",
    [85] = "Nightstinger",
    [86] = "Razorcreep",
    [87] = "Rift Runner",
    [88] = "Nightdweller",
    [89] = "Frostflare",
    [90] = "Cinderhoof",
    [91] = "Mouldpincer",
    [92] = "Bloodcurl",
    [93] = "Leafscuttler",
    [94] = "Sparkion",
    [95] = "Swamp Snapper",
    [96] = "Mould Shell",
    [97] = "Reed Lurker",
    [98] = "Neon Sparkid",
    [99] = "Vortexion",
    [100] = "Ivory Fang",
    [101] = "Shadow Claw",
    [102] = "Snow Pelt",
    [103] = "Jackalope",
    [104] = "Dreadhare",
    [105] = "Wolpertinger",
    [106] = "Stone Rhino",
    [107] = "Gold Sphinx",
    [108] = "Emerald Sphinx",
    [109] = "Shadow Sphinx",
    [110] = "Jungle Saurian",
    [111] = "Ember Saurian",
    [112] = "Lagoon Saurian",
    [113] = "Blazing Unicorn",
    [114] = "Arctic Unicorn",
    [115] = "Prismatic unicorn",
    [116] = "Cranium Spider",
    [117] = "Cave Tarantula",
    [118] = "Gloom Widow",
    [119] = "Mole",
    [120] = "Marsh Toad",
    [121] = "Sanguine Frog",
    [122] = "Toxic Toad",
    [123] = "Ebony Tiger",
    [124] = "Feral Tiger",
    [125] = "Jungle Tiger",
    [126] = "Fleeting Knowledge",
    [127] = "Tawny Owl",
    [128] = "Snowy Owl",
    [129] = "Boreal Owl",
    [130] = "Lacewing Moth",
    [131] = "Hibernal Moth",
    [132] = "Cold Percht Sleigh",
    [133] = "Bright Percht Sleigh",
    [134] = "Dark Percht Sleigh",
    [135] = "Festive Snowman",
    [136] = "Muffled Snowman",
    [137] = "Caped Snowman",
    [138] = "Rabbit Rickshaw",
    [139] = "Bunny Dray",
    [140] = "Cony Cart",
    [141] = "River Crocovile",
    [142] = "Swamp Crocovile",
    [143] = "Nightmarish Crocovile",
    [144] = "Gryphon",
    [145] = "Jousting Eagle",
    [146] = "Cerberus Champion",
    [147] = "Cold Percht Sleigh Variant",
    [148] = "Bright Percht Sleigh Variant",
    [149] = "Dark Percht Sleigh Variant",
    [150] = "Cold Percht Sleigh Final",
    [151] = "Bright Percht Sleigh Final",
    [152] = "Dark Percht Sleigh Final",
    [153] = "Battle Badger",
    [154] = "Ether Badger",
    [155] = "Zaoan Badger",
    [156] = "Blue Rolling Barrel",
    [157] = "Red Rolling Barrel",
    [158] = "Green Rolling Barrel",
    [159] = "Floating Sage",
    [160] = "Floating Scholar",
    [161] = "Floating Augur",
    [162] = "Haze",
    [163] = "Antelope",
    [164] = "Snow Strider",
    [165] = "Dusk Pryer",
    [166] = "Dawn Strayer",
    [167] = "Phantasmal Jade",
    [168] = "Savanna Ostrich",
    [169] = "Coral Rhea",
    [170] = "Eventide Nandu",
    [171] = "Voracious Hyaena",
    [172] = "Cunning Hyaena",
    [173] = "Scruffy Hyaena",
    [174] = "White Lion",
    [175] = "Krakoloss",
    [176] = "Merry Mammoth",
    [177] = "Holiday Mammoth",
    [178] = "Festive Mammoth",
    [179] = "Void Watcher",
    [180] = "Rune Watcher",
    [181] = "Rift Watcher",
    [182] = "Phant",
    [183] = "Shellodon",
    [184] = "Singeing Steed",
    [185] = "Hyacinth",
    [186] = "Peony",
    [187] = "Dandelion",
    [188] = "Rustwurm",
    [189] = "Bogwurm",
    [190] = "Gloomwurm",
    [191] = "Emerald Raven",
    [192] = "Mystic Raven",
    [193] = "Radiant Raven",
    [194] = "Gloothomotive",
    [195] = "Topaz Shrine",
    [196] = "Jade Shrine",
    [197] = "Obsidian Shrine",
    [198] = "Poppy ibex",
    [199] = "Mint ibex",
    [200] = "Cinnamon ibex",
    [201] = "Giant Beaver",
    [202] = "Noxious Ripptor",
    [203] = "Parade Horse",
    [204] = "Jousting Horse",
    [205] = "Tourney Horse",
    [206] = "Mutated Abomination",
    [207] = "Tangerine Flecked Koi",
    [208] = "Brass Speckled Koi",
    [209] = "Ink Spotted Koi",
    [210] = "Frostbringer",
    [211] = "Winterstride",
    [212] = "Icebreacher",
    [213] = "Boisterous Bull",
    [214] = "Surly Steer",
    [215] = "Obstinate Ox",
    [216] = "Darkfire Devourer",
    [217] = "Spirit of Purity",
    [218] = "Foxmouse",
    [219] = "Doom Skull",
    [220] = "Magma Skull",
    [221] = "Corpsefire Skull",
    [222] = "Mystic Jaguar",
    [223] = "Gorgon Hydra",
    [224] = "Dawnbringer Pegasus",
    [225] = "Wrathfire Pegasus",
    [226] = "Skybreaker Pegasus",
    [227] = "Pegasus",
    [228] = "Glacier Wyrm",
    [229] = "Bog Tyrant",
    [230] = "Crimson Fang",
    [231] = "Bumblebee",
    [232] = "Primal Demonosaur"
}

local randMountAction = Action("RandomMountForNewPlayers")

function randMountAction.onUse(player, item, fromPosition, target, toPosition, isHotkey)
    local availableMounts = {}
    for id, name in pairs(mounts) do
        if not player:hasMount(name) then -- Verificando pelo nome da montaria
            table.insert(availableMounts, name)
        end
    end

    if #availableMounts == 0 then
        player:sendTextMessage(MESSAGE_EVENT_ADVANCE, "Você já possui todas as montarias disponíveis!")
        return true
    end

    local randomMountName = availableMounts[math.random(#availableMounts)]

    if player:addMount(randomMountName) then
        player:removeItem(itemMountDollId, 1)
        player:sendTextMessage(MESSAGE_EVENT_ADVANCE, "Você recebeu a montaria " .. randomMountName .. "!")
    else
        player:sendTextMessage(MESSAGE_EVENT_ADVANCE, "Ocorreu um erro ao adicionar a montaria.")
    end
    return true
end

randMountAction:id(itemMountDollId)
randMountAction:register()